# shape

In [2]:
import numpy as np
scalar = np.array(3)
print(scalar)
print(scalar.shape)

3
()


In [2]:
vector = np.array([1,2,3])
print(vector.shape)

(3,)


# new axis

In [11]:

vector = np.array([1, 2, 3])  # 원본 벡터
column_vector = vector[:, np.newaxis]  # 전체 원소를 세로 방향으로 확장
first_element_column = vector[0, np.newaxis]  # 첫 번째 원소만 세로 방향으로 확장
range_column_vector = vector[1:3, np.newaxis]  # 일부 범위를 세로 방향으로 확장

print("vector:", vector)
print("vector.ndim:", vector.ndim)

print("column_vector:\n", column_vector)
print("column_vector.ndim:", column_vector.ndim)

print("first_element_column:\n", first_element_column) #scalar임
print("first_element_column.ndim:", first_element_column.ndim)

print("range_column_vector:\n", range_column_vector)
print("range_column_vector.ndim:", range_column_vector.ndim)


vector: [1 2 3]
vector.ndim: 1
column_vector:
 [[1]
 [2]
 [3]]
column_vector.ndim: 2
first_element_column:
 [1]
first_element_column.ndim: 1
range_column_vector:
 [[2]
 [3]]
range_column_vector.ndim: 2


In [15]:
range_column_vector_n = range_column_vector[:, np.newaxis]
print(range_column_vector_n)
print(range_column_vector_n.shape)

[[[2]]

 [[3]]]
(2, 1, 1)


# transpose

In [112]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr = arr.reshape(4,3,1)

In [113]:
arr

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [27]:
arr.transpose()

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]]])

In [28]:
arr.transpose().shape

(1, 4, 3)

# type 속성

In [29]:
array = np.array([10, 20, 30], dtype=np.int16)

print(array.dtype)    # 배열의 데이터 타입을 반환 출력: int16
print(array.itemsize) # 배열의 각 요소가 차지하는 바이트 크기 확인 출력: 2 
print(array.nbytes)   # 배열 전체의 메모리 사용량 확인 출력: 6 

int16
2
6


## 타입 변환

In [48]:
array = np.array([510, 2, 3], dtype=np.int32)

# int32 -> float64로 변환
converted_array = array.astype(np.float64)
print(converted_array.dtype)

# float64 -> int8로 변환 (데이터 손실 주의)
converted_int_array = converted_array.astype(np.int8)
print(converted_int_array)

float64
[-2  2  3]


# 인덱싱

In [31]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 특정 요소 접근
print(matrix[1, 2]) # 2행 3열

# 특정 행 전체 선택
print(matrix[0]) # 1행 전체

# 특정 열만 선택
print(matrix[:, 1]) # 모든 행의 2열

6
[1 2 3]
[2 5 8]


In [34]:
print(matrix[0,2])

3


In [35]:
print(matrix[[0,2]])

[[1 2 3]
 [7 8 9]]


In [36]:
print(matrix[[0,2],2])

[3 9]


In [41]:
print(matrix[[0,2],[0,2]])

[1 9]


In [45]:
array = np.array([10, 20, 30, 40])

# 특정 요소 수정
array[2] = 99
print(array)  # 출력: [10 20 99 40]

# 여러 요소 수정
array[1:3] = [55, 77]
print(array)  # 출력: [10 55 77 40]

[10 20 99 40]
[10 55 77 40]


# 연산

In [49]:
matrix = np.array([[1, 2], [3, 4]])    

# 전치 행렬
print('np.transpose(matrix): \n', np.transpose(matrix))

# 행렬 곱 (내적)
vector = np.array([2, 3])
print('np.dot(matrix, vector): ',np.dot(matrix, vector))#(2,2)@(2,)

# 역행렬 계산
inverse = np.linalg.inv(matrix)
print('np.linalg.inv(matrix): \n', inverse)

np.transpose(matrix): 
 [[1 3]
 [2 4]]
np.dot(matrix, vector):  [ 8 18]
np.linalg.inv(matrix): 
 [[-2.   1. ]
 [ 1.5 -0.5]]


# broadcasting

In [71]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])


In [72]:
%%timeit
a*b

263 ns ± 0.615 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [73]:
c = np.array([1.0,2.0,3.0])
d = np.array(2.0)

In [74]:
%%timeit
c*d

266 ns ± 0.789 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [70]:
c*d

array([2., 4., 6.])

In [88]:
from numpy import sum, array, argmin, sqrt

In [95]:
arr = np.array(range(1,9)).reshape(2,2,2)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [96]:
barr = np.array(range(1,3))

In [97]:
diff = arr-barr
diff

array([[[0, 0],
        [2, 2]],

       [[4, 4],
        [6, 6]]])

In [99]:
sum(diff, axis = 0)

array([[4, 4],
       [8, 8]])

In [100]:
sum(diff, axis = 1)

array([[ 2,  2],
       [10, 10]])

In [101]:
sum(diff, axis = 2)

array([[ 0,  4],
       [ 8, 12]])

In [107]:
diff[1,1,0]

np.int64(6)

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr = arr.reshape(2,2,3,1) #arr.shape == (2,2,3,1)
print(arr.shape)
arr = arr[:,:,np.newaxis] #arr.shape == (2,2,1,3,1)
print(arr.shape)

(2, 2, 3, 1)


(2, 2, 3, 1, 1)

In [119]:
arr = np.array(range(1,5))
arr = arr.reshape(2,2)
arr = arr[:,np.newaxis]

In [121]:
arr.shape

(2, 1, 2)

# pandas

In [1]:
import pandas as pd

In [2]:
data = {
    'name' : ['chris'],
    'age' : [28],
    'city' : ['seoul'],
}
df = pd.DataFrame(data)

In [3]:
df

name  age   city
0  chris   28  seoul

In [4]:
import pandas as pd

# 리스트를 이용한 생성
series_from_list = pd.Series([1, 2, 3, 4])
print("series_from_list:\n", series_from_list)

# 딕셔너리를 이용한 생성 (인덱스 지정)
series_from_dict = pd.Series({'a': 10, 'b': 20, 'c': 30})
print("series_from_dict:\n", series_from_dict)

# 인덱스와 함께 생성
series_with_index = pd.Series([100, 200, 300], index=['x', 'y', 'z'])
print("series_with_index:\n", series_with_index)

# 특정 데이터 타입 지정
series_with_dtype = pd.Series([1.5, 2.5, 3.5], dtype='float64')
print("series_with_dtype:\n", series_with_dtype)

series_from_list:
 0    1
1    2
2    3
3    4
dtype: int64
series_from_dict:
 a    10
b    20
c    30
dtype: int64
series_with_index:
 x    100
y    200
z    300
dtype: int64
series_with_dtype:
 0    1.5
1    2.5
2    3.5
dtype: float64


In [15]:
#series attribute
a = series_from_list
print(a.values) #type : ndarray
print(a.index)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.name)

[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)
int64
(4,)
4
None


In [59]:
# 성적 시리즈 생성
grades = pd.Series([85, 90, 78, 92], index=['국어', '영어', '수학', '과학'])



In [19]:
grades.describe()

count     4.000000
mean     86.250000
std       6.238322
min      78.000000
25%      83.250000
50%      87.500000
75%      90.500000
max      92.000000
dtype: float64

In [56]:
# 학생들의 성적 데이터 (10명)
data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당', '율곡이이', '정약용', '허준', '세종대왕'],
    '국어': [90, 85, 78, 92, 88, 95, 89, 91, 86, 93],
    '영어': [88, 92, 80, 90, 85, 93, 87, 90, 89, 91],
    '수학': [95, 87, 91, 94, 89, 92, 90, 93, 88, 94]
}

# 데이터프레임 생성
df = pd.DataFrame(data)
df

이름  국어  영어  수학
0   홍길동  90  88  95
1   김철수  85  92  87
2   박영희  78  80  91
3   이순신  92  90  94
4   강감찬  88  85  89
5  신사임당  95  93  92
6  율곡이이  89  87  90
7   정약용  91  90  93
8    허준  86  89  88
9  세종대왕  93  91  94

In [28]:
print(df.index)

RangeIndex(start=0, stop=10, step=1)


In [31]:
df = df.set_index('이름')

In [32]:
df.index

Index(['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당', '율곡이이', '정약용', '허준', '세종대왕'], dtype='object', name='이름')

In [34]:
df.loc['이순신':'신사임당']

국어  영어  수학
이름              
이순신   92  90  94
강감찬   88  85  89
신사임당  95  93  92

In [36]:
df.loc[['이순신','신사임당']]

국어  영어  수학
이름              
이순신   92  90  94
신사임당  95  93  92

In [58]:
df.iloc[3] #이순신 index = 3

이름    이순신
국어     92
영어     90
수학     94
Name: 3, dtype: object

In [45]:
df['국적'] = '한국'

In [46]:
df

국어  영어  수학  국적
이름                  
홍길동   90  88  95  한국
김철수   85  92  87  한국
박영희   78  80  91  한국
이순신   92  90  94  한국
강감찬   88  85  89  한국
신사임당  95  93  92  한국
율곡이이  89  87  90  한국
정약용   91  90  93  한국
허준    86  89  88  한국
세종대왕  93  91  94  한국

In [53]:
df.drop('국적', axis =1) #열벡터 삭제

국어  영어  수학
이름              
홍길동   90  88  95
김철수   85  92  87
박영희   78  80  91
이순신   92  90  94
강감찬   88  85  89
신사임당  95  93  92
율곡이이  89  87  90
정약용   91  90  93
허준    86  89  88
세종대왕  93  91  94

In [61]:
df.sum(axis=0)

이름    홍길동김철수박영희이순신강감찬신사임당율곡이이정약용허준세종대왕
국어                                 887
영어                                 885
수학                                 913
dtype: object

In [64]:
df = df.set_index('이름')

In [66]:
df.sum(axis=1)

이름
홍길동     273
김철수     264
박영희     249
이순신     276
강감찬     262
신사임당    280
율곡이이    266
정약용     274
허준      263
세종대왕    278
dtype: int64

In [67]:
df

국어  영어  수학
이름              
홍길동   90  88  95
김철수   85  92  87
박영희   78  80  91
이순신   92  90  94
강감찬   88  85  89
신사임당  95  93  92
율곡이이  89  87  90
정약용   91  90  93
허준    86  89  88
세종대왕  93  91  94

In [4]:
if not 1:
    print('hi')

In [2]:
if 2:
    print('hi')

hi


In [3]:
if 0:
    print('hi')