## Perceptron
- Perceptron with Linear Activation and Sigmoid Activation for Binary Classification

In [32]:
import numpy as np

# 입력 데이터 (예: AND 게이트 데이터셋)
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs = np.array([0, 0, 0, 1])

In [33]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [34]:
outputs

array([0, 0, 0, 1])

In [35]:
# 가중치와 편향 초기화
np.random.seed(1020)  
weights = np.random.rand(2) # [0,1)={x∈R ∣ 0 ≤ x < 1}
bias = np.random.rand(1)

In [36]:
weights # w_1, w_2

array([0.75895305, 0.16673132])

In [37]:
bias

array([0.6893323])

In [38]:
# 학습률과 에포크 설정
learning_rate = 0.1
epochs = 20

In [39]:
# 활성화 함수 정의
def step_function(x):
    return 1 if x >= 0 else 0

In [40]:
# 퍼셉트론 학습 (bias가 음수일때)
for epoch in range(epochs):
    for i in range(len(inputs)): # inputs = [[0, 0], [0, 1], [1, 0], [1, 1]]
        
        # 총 입력 계산 [0, 0] * [0.16501138, 0.17469313]
        total_input = np.dot(inputs[i], weights) + bias # 0*(0.16501138) + 0*(0.17469313)-0.33358941
        
        # 예측 출력 계산
        prediction = step_function(total_input)
        
        # 오차 계산 # outputs = [0, 0, 0, 1]
        error = outputs[i] - prediction # 0 정확한것
        print(f'inputs[i] : {inputs[i]}') # [0, 0]
        print(f'weights : {weights}') # [0.06501138 0.67469313]
        print(f'np.dot(inputs[i], weights) : {np.dot(inputs[i], weights)}')
        print(f'bias before update: {bias}')
        print(f'prediction: {prediction}')
        print(f'error: {error}') # 0, 1
        print(f'inputs[i]: {inputs[i]}')

        # 가중치와 편향 업데이트
        weights = weights + learning_rate * error * inputs[i] #  [0.16501138 0.17469313] + 0.1 * 0 * [0, 0]
        bias = bias + learning_rate * error # -0.33358941 + 0.1 * 0
        
        print(f'weights after update: {weights}')
        print(f'bias after update: {bias}')
        print('====\n')

inputs[i] : [0 0]
weights : [0.75895305 0.16673132]
np.dot(inputs[i], weights) : 0.0
bias before update: [0.6893323]
prediction: 1
error: -1
inputs[i]: [0 0]
weights after update: [0.75895305 0.16673132]
bias after update: [0.5893323]
====

inputs[i] : [0 1]
weights : [0.75895305 0.16673132]
np.dot(inputs[i], weights) : 0.16673131761969695
bias before update: [0.5893323]
prediction: 1
error: -1
inputs[i]: [0 1]
weights after update: [0.75895305 0.06673132]
bias after update: [0.4893323]
====

inputs[i] : [1 0]
weights : [0.75895305 0.06673132]
np.dot(inputs[i], weights) : 0.7589530465963981
bias before update: [0.4893323]
prediction: 1
error: -1
inputs[i]: [1 0]
weights after update: [0.65895305 0.06673132]
bias after update: [0.3893323]
====

inputs[i] : [1 1]
weights : [0.65895305 0.06673132]
np.dot(inputs[i], weights) : 0.7256843642160951
bias before update: [0.3893323]
prediction: 1
error: 0
inputs[i]: [1 1]
weights after update: [0.65895305 0.06673132]
bias after update: [0.389332

In [41]:
# 예측 함수 정의
def predict(input_data):
    total_input = np.dot(input_data, weights) + bias # [0, 0] * [0.16325556 0.10282544] + (-0.18059453)
    return step_function(total_input)

In [42]:
# 퍼셉트론 학습 (bias가 양수일때, 실행시키면 안됨)
for epoch in range(epochs):
    for i in range(len(inputs)): # [0, 0], [0, 1], [1, 0], [1, 1]
        # 총 입력 계산
        total_input = np.dot(inputs[i], weights) + bias # 0*0.16501138 + 0*0.17469313 + 0.33358941 # 0.33358941
        # 예측 출력 계산
        prediction = step_function(total_input) # 1
        # 오차 계산 # [0, 0, 0, 1]
        error = outputs[i] - prediction
        # print(f'inputs[i] : {inputs[i]}') # [0, 0]
        # print(f'weights : {weights}') # [0.06501138 0.67469313]
        # print(f'np.dot(inputs[i], weights) : {np.dot(inputs[i], weights)}') # 0
        # print(f'bias before update: {bias}') # 0.33358941
        # print(f'prediction: {prediction}') # 1
        # print(f'error: {error}') # -1
        # print(f'inputs[i]: {inputs[i]}')

        # 가중치와 편향 업데이트
        weights = weights + learning_rate * error * inputs[i] # [0.16501138 0.17469313] + 0.1 * -1 * [0, 0]
        bias = bias + learning_rate * error # 0.33358941 + (0.1*(-1)=-0.1) = 0.233348941
        # print(f'weights after update: {weights}')
        # print(f'bias after update: {bias}')
        # print('====')

# 학습 결과 출력 (실패하는 경우)
print("학습된 가중치 (실패):", weights)
print("학습된 편향 (실패):", bias)

# 예측 함수 정의 (함수를 먼저 정의)
def predict_fail(input_data):
    total_input = np.dot(input_data, weights) + bias
    return step_function(total_input)

# 예측 결과 확인 (실패하는 경우)
print("\n예측 결과 (실패):")
for input_data in inputs: # [0, 0], [0, 1], [1, 0], [1, 1]
    print(f"입력: {input_data}, 예측 출력: {predict_fail(input_data)}")

학습된 가중치 (실패): [0.25895305 0.06673132]
학습된 편향 (실패): [-0.3106677]

예측 결과 (실패):
입력: [0 0], 예측 출력: 0
입력: [0 1], 예측 출력: 0
입력: [1 0], 예측 출력: 0
입력: [1 1], 예측 출력: 1


In [43]:
# 학습 결과 출력
print("학습된 가중치:", weights)
print("학습된 편향:", bias)

학습된 가중치: [0.25895305 0.06673132]
학습된 편향: [-0.3106677]


In [44]:
# 예측 결과 확인
for input_data in inputs: # [0, 0], [0, 1], [1, 0], [1, 1]
    print(f"입력: {input_data}, 예측 출력: {predict(input_data)}")

입력: [0 0], 예측 출력: 0
입력: [0 1], 예측 출력: 0
입력: [1 0], 예측 출력: 0
입력: [1 1], 예측 출력: 1
