# 과제

In [12]:
import numpy as np
n_arr = np.arange(1,10).reshape(3,3)
n_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
import random
r_arr = np.array([random.random() for _ in range(10)]).reshape(2,5)
r_arr

array([[0.73456283, 0.35763926, 0.42065253, 0.9001121 , 0.99326098],
       [0.26291897, 0.35978699, 0.9247128 , 0.99872457, 0.85031046]])

In [14]:
print(f'자연수 배열 총합 : {n_arr.sum()}')
print(f'실수 배열 총합 : {r_arr.sum()}')
print(f'자연수 배열 평균 : {n_arr.mean()}')
print(f'실수 배열 평균 : {r_arr.mean()}')

자연수 배열 총합 : 45
실수 배열 총합 : 6.802681492483883
자연수 배열 평균 : 5.0
실수 배열 평균 : 0.6802681492483883


In [15]:
n_arr_diag = np.diag(n_arr)
print(n_arr@n_arr_diag)

[ 38  83 128]


In [16]:
import pandas as pd

In [17]:
dic = {
    'Name': ['Alice', 'Bob', None, 'Charlie'],
    'Age': [25, None, 28, 35],
    'City': ['New York', None, 'Chicago', None]
}


In [18]:
df = pd.DataFrame.from_dict(dic)
df

Name   Age      City
0    Alice  25.0  New York
1      Bob   NaN      None
2     None  28.0   Chicago
3  Charlie  35.0      None

In [19]:
df['Name'] = df['Name'].fillna('Unknown')
df['Age'] = df['Age'].fillna(df['Age'].mean())
# df = df.fillna({'Name':'Unknown', 'Age':df['Age'].mean()})

In [20]:
df

Name        Age      City
0    Alice  25.000000  New York
1      Bob  29.333333      None
2  Unknown  28.000000   Chicago
3  Charlie  35.000000      None

In [21]:
import requests
import json
re = requests.get('https://jsonplaceholder.typicode.com/todos')

In [22]:
if re.status_code == 200: #정상
    data_json = re.json() #json으로
    print(data_json)
else:
    print(f'http 상태 : {re.status_code}')

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}, {'userId': 1, 'id': 2, 'title': 'quis ut nam facilis et officia qui', 'completed': False}, {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False}, {'userId': 1, 'id': 4, 'title': 'et porro tempora', 'completed': True}, {'userId': 1, 'id': 5, 'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum', 'completed': False}, {'userId': 1, 'id': 6, 'title': 'qui ullam ratione quibusdam voluptatem quia omnis', 'completed': False}, {'userId': 1, 'id': 7, 'title': 'illo expedita consequatur quia in', 'completed': False}, {'userId': 1, 'id': 8, 'title': 'quo adipisci enim quam ut ab', 'completed': True}, {'userId': 1, 'id': 9, 'title': 'molestiae perspiciatis ipsa', 'completed': False}, {'userId': 1, 'id': 10, 'title': 'illo est ratione doloremque quia maiores aut', 'completed': True}, {'userId': 1, 'id': 11, 'title': 'vero rerum temporibus dolor', 'completed': True}, {'userId': 1, 'i

In [23]:
with open ('read_http.json','w') as f:
    tmp = json.dumps(data_json)
    f.write(tmp)

In [24]:
with open('read_http.json','r') as f:
    data = json.load(f)

In [25]:
df = pd.DataFrame(data)
df['title']

0                                     delectus aut autem
1                     quis ut nam facilis et officia qui
2                                    fugiat veniam minus
3                                       et porro tempora
4      laboriosam mollitia et enim quasi adipisci qui...
                             ...                        
195                  consequuntur aut ut fugit similique
196                    dignissimos quo nobis earum saepe
197                         quis eius est sint explicabo
198                         numquam repellendus a magnam
199                         ipsam aperiam voluptates qui
Name: title, Length: 200, dtype: object

# 미니퀘스트

In [26]:
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array.ndim)

3


In [27]:
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
import numpy as np
array = np.array([7, 14, 21])
array = array[:, np.newaxis]
array

array([[ 7],
       [14],
       [21]])

In [29]:
print(array.ndim)

2


In [30]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
array.shape

(2, 3)

In [31]:
arr = np.array([10, 20, 30, 40, 50, 60]).reshape(2,3)
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [33]:
import numpy as np
array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
array.shape

(3, 2, 2)

In [34]:
array.reshape(3,4)
array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [35]:
res = [0]
if res:
    print('hi')

hi
